#import "LGMetalShaderSource.h"

NSString *LGGlassMetalSource(void) {
    static NSString * const source = @"// fullscreen quad + glass shading\n"
        "// kept as a string so the tweak can compile it at runtime\n"
        "\n"
        "#include <metal_stdlib>\n"
        "using namespace metal;\n"
        "\n"
        "struct Uniforms {\n"
        "    float2 resolution;\n"
        "    float2 screenResolution;\n"
        "    float2 cardOrigin;\n"
        "    float2 wallpaperResolution;\n"
        "    float  radius;\n"
        "    float  bezelWidth;\n"
        "    float  glassThickness;\n"
        "    float  refractionScale;\n"
        "    float  refractiveIndex;\n"
        "    float  specularOpacity;\n"
        "    float  specularAngle;\n"
        "    float  blur;\n"
        "    float2 wallpaperOrigin;\n"
        "    float  samplingOrientation;\n"
        "    float  hasShapeMask;\n"
        "};\n"
        "\n"
        "float surfaceConvexSquircle(float x) { return pow(1.0 - pow(1.0 - x, 4.0), 0.25); }\n"
        "float2 refractRay(float2 normal, float eta) {\n"
        "    float cosI = -normal.y;\n"
        "    float k    = 1.0 - eta * eta * (1.0 - cosI * cosI);\n"
        "    if (k < 0.0) return float2(0.0);\n"
        "    float kSqrt = sqrt(k);\n"
        "    return float2(\n"
        "        -(eta * cosI + kSqrt) * normal.x,\n"
        "         eta - (eta * cosI + kSqrt) * normal.y\n"
        "    );\n"
        "}\n"
        "\n"
        "float rawRefraction(float bezelRatio, float glassThickness, float bezelWidth, float eta) {\n"
        "    float x     = clamp(bezelRatio, 0.05, 0.95);\n"
        "    float y     = surfaceConvexSquircle(x);\n"
        "    float y2    = surfaceConvexSquircle(x + 0.001);\n"
        "    float deriv = (y2 - y) / 0.001;\n"
        "    float mag   = sqrt(deriv * deriv + 1.0);\n"
        "    float2 n    = float2(-deriv / mag, -1.0 / mag);\n"
        "    float2 r    = refractRay(n, eta);\n"
        "    if (length(r) < 0.0001 || abs(r.y) < 0.0001) return 0.0;\n"
        "    float remaining = y * bezelWidth + glassThickness;\n"
        "    return r.x * (remaining / r.y);\n"
        "}\n"
        "\n"
        "float displacementAtRatio(float bezelRatio, float glassThickness, float bezelWidth, float eta) {\n"
        "    float peak = rawRefraction(0.05, glassThickness, bezelWidth, eta);\n"
        "    if (abs(peak) < 0.0001) return 0.0;\n"
        "    float raw     = rawRefraction(bezelRatio, glassThickness, bezelWidth, eta);\n"
        "    float norm    = raw / peak;\n"
        "    float falloff = 1.0 - smoothstep(0.0, 1.0, bezelRatio);\n"
        "    return norm * falloff;\n"
        "}\n"
        "\n"
        "float linearizeSRGB(float c) {\n"
        "    return c > 0.04045 ? pow((c + 0.055) / 1.055, 2.4) : c / 12.92;\n"
        "}\n"
        "\n"
        "float gammaCorrectSRGB(float c) {\n"
        "    return c <= 0.0031308 ? 12.92 * c : 1.055 * pow(c, 1.0 / 2.4) - 0.055;\n"
        "}\n"
        "\n"
        "float3 srgbToXyz(float3 rgb) {\n"
        "    float3 lin = float3(linearizeSRGB(rgb.r), linearizeSRGB(rgb.g), linearizeSRGB(rgb.b));\n"
        "    return float3(\n"
        "        dot(lin, float3(0.4124, 0.3576, 0.1805)),\n"
        "        dot(lin, float3(0.2126, 0.7152, 0.0722)),\n"
        "        dot(lin, float3(0.0193, 0.1192, 0.9505))\n"
        "    );\n"
        "}\n"
        "\n"
        "float3 xyzToSrgb(float3 xyz) {\n"
        "    float3 lin = float3(\n"
        "        dot(xyz, float3( 3.2406, -1.5372, -0.4986)),\n"
        "        dot(xyz, float3(-0.9689,  1.8758,  0.0415)),\n"
        "        dot(xyz, float3( 0.0557, -0.2040,  1.0570))\n"
        "    );\n"
        "    return clamp(float3(gammaCorrectSRGB(lin.r), gammaCorrectSRGB(lin.g), gammaCorrectSRGB(lin.b)), 0.0, 1.0);\n"
        "}\n"
        "\n"
        "float labF(float t) {\n"
        "    return t > 0.00885645167 ? pow(t, 1.0 / 3.0) : (7.787037 * t + 16.0 / 116.0);\n"
        "}\n"
        "\n"
        "float labInvF(float t) {\n"
        "    float t3 = t * t * t;\n"
        "    return t3 > 0.00885645167 ? t3 : (t - 16.0 / 116.0) / 7.787037;\n"
        "}\n"
        "\n"
        "float3 xyzToLab(float3 xyz) {\n"
        "    float3 n = xyz / float3(0.95047, 1.0, 1.08883);\n"
        "    float fx = labF(n.x), fy = labF(n.y), fz = labF(n.z);\n"
        "    return float3(116.0 * fy - 16.0, 500.0 * (fx - fy), 200.0 * (fy - fz));\n"
        "}\n"
        "\n"
        "float3 labToXyz(float3 lab) {\n"
        "    float fy = (lab.x + 16.0) / 116.0;\n"
        "    float fx = fy + lab.y / 500.0;\n"
        "    float fz = fy - lab.z / 200.0;\n"
        "    return float3(0.95047 * labInvF(fx), labInvF(fy), 1.08883 * labInvF(fz));\n"
        "}\n"
        "\n"
        "float3 srgbToLch(float3 rgb) {\n"
        "    float3 lab = xyzToLab(srgbToXyz(rgb));\n"
        "    return float3(lab.x, length(lab.yz), atan2(lab.z, lab.y));\n"
        "}\n"
        "\n"
        "float3 lchToSrgb(float3 lch) {\n"
        "    float3 lab = float3(lch.x, cos(lch.z) * lch.y, sin(lch.z) * lch.y);\n"
        "    return xyzToSrgb(labToXyz(lab));\n"
        "}\n"
        "\n"
        "float maskAlphaAt(texture2d<float> tex, sampler s, float2 uv) {\n"
        "    return tex.sample(s, clamp(uv, 0.0, 1.0)).a;\n"
        "}\n"
        "\n"
        "struct MaskEdgeInfo {\n"
        "    float distance;\n"
        "    float2 dir;\n"
        "    float alpha;\n"
        "};\n"
        "\n"
        "MaskEdgeInfo estimateMaskEdgeDistance(texture2d<float> tex, sampler s, float2 uv) {\n"
        "    MaskEdgeInfo info;\n"
        "    float center = maskAlphaAt(tex, s, uv);\n"
        "    info.alpha = center;\n"
        "    float2 texel = 1.0 / float2(tex.get_width(), tex.get_height());\n"
        "    float2 grad = float2(\n"
        "        maskAlphaAt(tex, s, uv + float2(texel.x, 0.0)) - maskAlphaAt(tex, s, uv - float2(texel.x, 0.0)),\n"
        "        maskAlphaAt(tex, s, uv + float2(0.0, texel.y)) - maskAlphaAt(tex, s, uv - float2(0.0, texel.y))\n"
        "    );\n"
        "    float2 dir = length(grad) > 0.0001 ? -normalize(grad) : float2(0.0, -1.0);\n"
        "    info.dir = dir;\n"
        "    if (center < 0.01) {\n"
        "        info.distance = 1e6;\n"
        "        return info;\n"
        "    }\n"
        "\n"
        "    float minDist = 1e6;\n"
        "    const int maxSteps = 10;\n"
        "    const float threshold = 0.5;\n"
        "    float2 dirs[8] = {\n"
        "        float2(1.0, 0.0), float2(-1.0, 0.0), float2(0.0, 1.0), float2(0.0, -1.0),\n"
        "        normalize(float2(1.0, 1.0)), normalize(float2(-1.0, 1.0)), normalize(float2(1.0, -1.0)), normalize(float2(-1.0, -1.0))\n"
        "    };\n"
        "    for (int i = 0; i < 8; i++) {\n"
        "        float2 d = dirs[i];\n"
        "        for (int step = 1; step <= maxSteps; step++) {\n"
        "            float2 offset = float(step) * texel * d;\n"
        "            float a = maskAlphaAt(tex, s, uv + offset);\n"
        "            if (a < threshold) {\n"
        "                minDist = min(minDist, length(offset * float2(tex.get_width(), tex.get_height())));\n"
        "                break;\n"
        "            }\n"
        "        }\n"
        "    }\n"
        "    info.distance = minDist;\n"
        "    return info;\n"
        "}\n"
        "\n"
        "struct VertexOut {\n"
        "    float4 position [[position]];\n"
        "    float2 localUV;\n"
        "};\n"
        "\n"
        "vertex VertexOut vertexShader(uint vid [[vertex_id]]) {\n"
        "    float2 pos[6] = {\n"
        "        float2(-1,-1), float2(1,-1), float2(-1,1),\n"
        "        float2(-1, 1), float2(1,-1), float2(1, 1)\n"
        "    };\n"
        "    float2 uv[6] = {\n"
        "        float2(0,1), float2(1,1), float2(0,0),\n"
        "        float2(0,0), float2(1,1), float2(1,0)\n"
        "    };\n"
        "    VertexOut out;\n"
        "    out.position = float4(pos[vid], 0, 1);\n"
        "    out.localUV  = uv[vid];\n"
        "    return out;\n"
        "}\n"
        "\n"
        "fragment float4 fragmentShader(VertexOut in [[stage_in]], texture2d<float> blurredTex [[texture(0)]], texture2d<float> maskTex [[texture(1)]], constant Uniforms& u [[buffer(0)]]) {\n"
        "    constexpr sampler s(filter::linear, address::clamp_to_edge);\n"
        "    float2 px = in.localUV * u.resolution;\n"
        "    float W = u.resolution.x, H = u.resolution.y;\n"
        "    float R = u.radius, bezel = u.bezelWidth;\n"
        "    float eta = 1.0 / u.refractiveIndex;\n"
        "    bool useShapeMask = u.hasShapeMask > 0.5;\n"
        "    bool inLeft = px.x < R, inRight = px.x > W - R;\n"
        "    bool inTop = px.y < R, inBottom = px.y > H - R;\n"
        "    bool inCorner = (inLeft || inRight) && (inTop || inBottom);\n"
        "    float cx = inLeft ? px.x - R : inRight ? px.x - (W - R) : 0.0;\n"
        "    float cy = inTop ? px.y - R : inBottom ? px.y - (H - R) : 0.0;\n"
        "    float distFromCenter = length(float2(cx, cy));\n"
        "    if (inCorner && distFromCenter > R + 1.0) discard_fragment();\n"
        "    float distFromSide;\n"
        "    float2 dir;\n"
        "    if (inCorner) {\n"
        "        distFromSide = max(0.0, R - distFromCenter);\n"
        "        dir = distFromCenter > 0.001 ? normalize(float2(cx, cy)) : float2(0);\n"
        "    } else {\n"
        "        float dL = px.x, dR = W - px.x, dT = px.y, dB = H - px.y;\n"
        "        float dMin = min(min(dL, dR), min(dT, dB));\n"
        "        distFromSide = dMin;\n"
        "        dir = float2(\n"
        "            (dL < dR && dL == dMin) ? -1.0 : (dR <= dL && dR == dMin) ? 1.0 : 0.0,\n"
        "            (dT < dB && dT == dMin) ? -1.0 : (dB <= dT && dB == dMin) ? 1.0 : 0.0\n"
        "        );\n"
        "    }\n"
        "    float edgeOpacity = inCorner ? clamp(1.0 - max(0.0, distFromCenter - R), 0.0, 1.0) : 1.0;\n"
        "    float bezelRatio = clamp(distFromSide / bezel, 0.0, 1.0);\n"
        "    float edgeBand = 1.0;\n"
        "    if (useShapeMask) {\n"
        "        MaskEdgeInfo edgeInfo = estimateMaskEdgeDistance(maskTex, s, in.localUV);\n"
        "        float maskAlpha = edgeInfo.alpha;\n"
        "        float edgeDistance = edgeInfo.distance;\n"
        "        dir = edgeInfo.dir;\n"
        "        if (maskAlpha < 0.01) discard_fragment();\n"
        "        float edgeRadius = max(1.0, bezel * 0.35);\n"
        "        edgeBand = clamp(1.0 - (edgeDistance / edgeRadius), 0.0, 1.0);\n"
        "        edgeOpacity = maskAlpha;\n"
        "        bezelRatio = clamp(edgeDistance / edgeRadius, 0.0, 1.0);\n"
        "        distFromSide = bezel * bezelRatio;\n"
        "    }\n"
        "    float normDisp = ((useShapeMask ? edgeBand > 0.001 : distFromSide < bezel)) ? displacementAtRatio(bezelRatio, u.glassThickness, bezel, eta) : 0.0;\n"
        "    float dispStrength = useShapeMask ? edgeBand : edgeOpacity;\n"
        "    float2 dispPx = -dir * normDisp * bezel * u.refractionScale * dispStrength;\n"
        "    float2 screenPx = u.cardOrigin + px + dispPx;\n"
        "    float2 imgPx = screenPx - u.wallpaperOrigin;\n"
        "    float2 sampleUV = imgPx / u.wallpaperResolution;\n"
        "    int orientation = int(round(u.samplingOrientation));\n"
        "    if (orientation == 2) {\n"
        "        sampleUV = float2(1.0 - sampleUV.x, 1.0 - sampleUV.y);\n"
        "    } else if (orientation == 3) {\n"
        "        sampleUV = float2(1.0 - sampleUV.y, sampleUV.x);\n"
        "    } else if (orientation == 4) {\n"
        "        sampleUV = float2(sampleUV.y, 1.0 - sampleUV.x);\n"
        "    }\n"
        "    sampleUV = clamp(sampleUV, 0.0, 1.0);\n"
        "    float4 bgColor = blurredTex.sample(s, sampleUV);\n"
        "    float2 prismOffset = dispPx / max(u.wallpaperResolution, float2(1.0));\n"
        "    float dispersion = clamp(length(prismOffset) * 24.0, 0.0, 0.012);\n"
        "    float2 redUV = clamp(sampleUV - prismOffset * 0.55, 0.0, 1.0);\n"
        "    float2 blueUV = clamp(sampleUV + prismOffset * 0.55, 0.0, 1.0);\n"
        "    float3 dispersed = float3(\n"
        "        blurredTex.sample(s, mix(sampleUV, redUV, dispersion * 80.0)).r,\n"
        "        bgColor.g,\n"
        "        blurredTex.sample(s, mix(sampleUV, blueUV, dispersion * 80.0)).b\n"
        "    );\n"
        "    bgColor.rgb = mix(bgColor.rgb, dispersed, dispersion * 0.65);\n"
        "    float2 lightDir = float2(cos(u.specularAngle), -sin(u.specularAngle));\n"
        "    float specDot = dot(dir, lightDir);\n"
        "    float strokePx = 2.0;\n"
        "    float strokeMask = useShapeMask ? edgeBand : clamp(1.0 - (distFromSide / strokePx), 0.0, 1.0);\n"
        "    float lobeStart = 0.66;\n"
        "    float lobeWidth = 0.20;\n"
        "    float primary = smoothstep(lobeStart, lobeStart + lobeWidth, specDot);\n"
        "    float secondary = smoothstep(lobeStart, lobeStart + lobeWidth, -specDot);\n"
        "    float cornerSpec = smoothstep(0.46, 0.90, abs(specDot));\n"
        "    float specLobe = useShapeMask ? max(primary, secondary) : (inCorner ? cornerSpec : (primary + secondary));\n"
        "    float fresnel = pow(clamp(1.0 - bezelRatio, 0.0, 1.0), 2.2) * (useShapeMask ? edgeBand : edgeOpacity);\n"
        "    float specular = specLobe * strokeMask * u.specularOpacity * (useShapeMask ? 1.15 : 2.15) * edgeOpacity;\n"
        "    float highlight = specular + fresnel * (useShapeMask ? 0.28 : 0.34);\n"
        "    float3 lch = srgbToLch(clamp(bgColor.rgb, 0.0, 1.0));\n"
        "    lch.x = clamp(lch.x + highlight * (useShapeMask ? 18.0 : 36.0), 0.0, 100.0);\n"
        "    lch.y = max(0.0, lch.y - highlight * (useShapeMask ? 4.0 : 9.0));\n"
        "    float3 shapedHighlight = lchToSrgb(lch);\n"
        "    bgColor.rgb = mix(bgColor.rgb, shapedHighlight, clamp(highlight * (useShapeMask ? 0.48 : 0.70), 0.0, 1.0));\n"
        "    return float4(bgColor.rgb, edgeOpacity);\n"
        "}\n";
    return source;
}
